project:
  type: website
  output-dir: _site

website:
  title: "Python & data"
  description: "Introduction à la programmation Python et à l'écosystème data"
  site-url: https://surybang.github.io/python-data/
  repo-url: https://github.com/surybang/python-data
  repo-actions: [edit, issue]
  page-navigation: true
  back-to-top-navigation: true

  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/surybang/python-data
        aria-label: GitHub

  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Accueil
      - section: "Introduction"
        contents:
          - text: "Langages de programmation"
            href: 01-introduction/01-langages.qmd
          - text: "Pourquoi Python ?"
            href: 01-introduction/02-pourquoi-python.qmd
      - section: "Environnement"
        href: 02-environnement/index.qmd
        contents:
          - text: "Installer en local"
            href: 02-environnement/01-local.qmd
          - text: "Environnements en ligne"
            href: 02-environnement/02-cloud.qmd
      - section: "Initiation Python"
        href: 03-initiation-python/index.qmd
        contents:
          - text: "Premiers pas en notebook"
            href: 03-initiation-python/00-premiers-pas-notebooks.qmd
          - text: "Variables, types & opérations"
            href: 03-initiation-python/01-variables-types-operations.qmd
          - text: "Le slicing"
            href: 03-initiation-python/07-slicing.qmd

  page-footer:
    left: "Fabien HOS 👩🏻‍💻"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: style.css
    toc: true
    code-copy: true
    fig-align: center

execute:
  freeze: auto