project:
  type: website
  output-dir: _site

website:
  title: "Python & data"
  description: "Introduction à la programmation Python et à l'écosystème data"
  site-url: https://surybang.github.io/python-data/
  repo-url: https://github.com/surybang/python-data

  navbar:
    background: primary
    search: true
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Introduction"
        href: 01-introduction/index.qmd
      - text: "Environnement"
        href: 02-environnement/index.qmd
    right:
      - icon: github
        href: https://github.com/surybang/python-data
        aria-label: GitHub

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - 01-introduction/index.qmd
          - 01-introduction/01-langages.qmd
          - 01-introduction/02-pourquoi-python.qmd
          - 01-introduction/03-ecosysteme.qmd
      - section: "Environnement"
        contents:
          - 02-environnement/index.qmd
      - section: "Pour aller plus loin"
        contents:
          - text: "GitHub du cours"
            href: https://github.com/surybang/python-data

  page-footer:
    left: "Fabien HOS 👩🏻‍💻"
    right:
      - icon: github
        href: https://github.com/surybang/python-data

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: style.css
    toc: true
    code-fold: true
    code-copy: true
    fig-align: center

execute:
  freeze: auto

jupyter: python3