---
title: "Python pour la Data 🐍"
---

Bienvenue dans ce cours d'introduction à la programmation `Python` et à l'écosystème data.

## Objectifs

Ce cours est conçu pour des **débutants complets**. Il couvre dans un premier temps :

1. **Introduction** : Qu'est-ce qu'un langage de programmation ? Pourquoi Python ?
2. **L'environnement de développement**: Avoir un environnement fonctionnel pour Python
3. **Premiers pas** : Variables, types de base
4. **Conditions et boucles** : Prendre des décisions, répéter des actions
5. **Fonctions** : Organiser son code
6. **Structure de données** : Manipuler des données dans des objets appropriés

Dans un second temps, nous allons nous concentrer sur les packages `Numpy` et `Pandas`, des éléments centraux dans l'écosystème de `Python` pour la data.

Je vous invite également à prendre connaissance de la rubrique `Tutoriels` qui présentera divers packages utiles.

## Comment utiliser ce cours

Suivez les chapitres dans l'ordre via la barre latérale. Chaque notebook est interactif : vous pouvez lire, exécuter, modifier et expérimenter.

::: {.callout-tip}
## L'erreur est normale
Se tromper fait partie de l'apprentissage. Lisez les messages d'erreur, ils vous guident.
:::

## Ressources

- [Documentation officielle Python](https://docs.python.org/fr/3/)
- [GitHub du cours](https://github.com/surybang/python-data)
- [Galiana, Lino. 2025. Python pour la data science.](https://doi.org/10.5281/zenodo.8229676.)